### ISSUE TITLE
Fav System

### ISSUE THREAD

**Issue by t0bbl** [t0bbl/capstone-project#10]
## Value proposition

As a user
I want to favorit random designs
in order to find them again later on 

## Description

![Screenshot 2023-04-26 at 16 32 25](https://user-images.githubusercontent.com/117731660/234609083-d766ff10-9111-42ed-b098-ad4bb6f58675.png)

## Acceptance criteria

- [ ] i show a clickable fav button
- [ ] i save the state of fav to the localstorage

## Tasks

- [ ] Branch
- [ ] create the visuals for the fav 
- [ ] save the fav to local storage

**Comment by KivancUlucan** [comment]
LGTM!
