### ISSUE TITLE
setup mongoDB 

### ISSUE THREAD

**Issue by t0bbl** [t0bbl/capstone-project#12]
## Value proposition

As a dev
I want to add a local test mongodb with pictures and tags
in order to be able to test and program some of the features needed. 

## Acceptance criteria

- [ ] mongoDB up and running 
- [ ] temporary schema up and running

## Tasks

- [ ] setup mongoDB with compass
- [ ] setup dbconnect
- [ ] implement temporary schema
