### ISSUE TITLE
refactoring all the links

### ISSUE THREAD

**Issue by t0bbl** [t0bbl/capstone-project#13]
## Value proposition

As a dev
I want to refactor all links to my mongoDB
in order to fully utilize the DB and get the page to work properly

## Acceptance criteria

- [ ] the page still works as intended

## Tasks

- [ ] work the schema, states and fetches into the page
- [ ] ensure that the DB is working and structured as intended

**Comment by t0bbl** [comment]
since the DB should be filled with images from an AI its still filled with placeholder.
