### ISSUE TITLE
Implement AI

### ISSUE THREAD

**Issue by t0bbl** [t0bbl/capstone-project#15]
## Value proposition

As a user
I want to generate pictures via OpenAI 
in order to get a unique shirt design.

## Acceptance criteria

- [ ] the page still works as before but with the AI generated images

## Tasks

- [ ] form takes the keywords to the database
- [ ]  they are used for  a prompt for openAI
- [ ] i fetch the links coming back and safe them in my DB
- [ ] i render the page with the AI images

**Comment by Roland-Hufnagel** [comment]
Du brauchst dafür keine Developer-Story, denn es ist ein klarer User profit, echte AI-generierte Daten zu kriegen. Bitte schreibe die Story so, dass 'ein anderer Entwickler' eine klare Anweisung bekommt, was er tun soll und wie du kontrollierst, ob alles erfüllt ist.

**Comment by t0bbl** [comment]
> Du brauchst dafür keine Developer-Story, denn es ist ein klarer User profit, echte AI-generierte Daten zu kriegen. Bitte schreibe die Story so, dass 'ein anderer Entwickler' eine klare Anweisung bekommt, was er tun soll und wie du kontrollierst, ob alles erfüllt ist.

Fixed!

**Comment by Roland-Hufnagel** [comment]
This looks really better! Great. Happy Hacking...
