### ISSUE TITLE
Variations of Picture

### ISSUE THREAD

**Issue by t0bbl** [t0bbl/capstone-project#19]
## Value proposition

As a user
I want to get 4 variations of my favorit generated picture
in order to get a variety of pictures to choose from. 

## Description

![Screenshot 2023-04-25 at 15 01 10](https://github.com/t0bbl/capstone-project/assets/117731660/5c878661-d5e8-4a30-8a96-5fad3d45d8dd)
![Screenshot 2023-05-11 at 15 53 03](https://github.com/t0bbl/capstone-project/assets/117731660/dd5819f7-911b-45a3-add4-98274c65d1f7)

## Acceptance criteria

- [ ] i can click on the Variations button
- [ ] while i wait there is a "is loading" displayed
- [ ] i get my 4 variations shown

## Tasks

- [ ] rework the API endpoint to send the correct prompt to dall E
- [ ] add a "is loading"
