### ISSUE TITLE
Loading Page

### ISSUE THREAD

**Issue by t0bbl** [t0bbl/capstone-project#21]
## Value proposition

As a user
I want to have a pretty loading page
in order to be entertained while waiting for the AI.

## Description
![Screenshot 2023-05-15 at 11 40 17](https://github.com/t0bbl/capstone-project/assets/117731660/6b3f52c1-08f0-4590-84c9-a2b3b21d41a4)

## Acceptance criteria

- [ ] when the user clicks something that needs time to load a pulsating text is shown

## Tasks

- [ ] rework design
- [ ] establish isLoading state
- [ ] implement checks for loading and display accordingly
