### ISSUE TITLE
user Login

### ISSUE THREAD

**Issue by t0bbl** [t0bbl/capstone-project#25]
## Value proposition

As a user
I want to have my own login
in order to safe my favorites.

## Description

next/auth login and profile for user

## Acceptance criteria

- [ ] the user can create an account
- [ ] login
- [ ] logout
- [ ] favorites get saved in the account

## Tasks

- [ ] branch
- [ ] register and login page
- [ ] logout button
- [ ] myFavorites page

**Comment by mbosselmann** [comment]
Hi Robin,
nice try, but I have some remarks for you:
- It would be nice to see some wireframes where you share how the login will look like for the user and the different states (what the user will see if the user is not logged in and what the user will see if the user is logged in)
Try to think about more descriptive acceptance criteria (how can the user login/ logout, which informations need to be presented by the person etc.)

I hope this does help! :)

**Comment by HenrikeStahlhut** [comment]
Wireframes look good, nice work 🏋🏻‍♀️
