### ISSUE TITLE
save Favorits to Cloudinary

### ISSUE THREAD

**Issue by t0bbl** [t0bbl/capstone-project#26]
## Value proposition

As a dev
I want to save favorits in cloudinary
in order to keep them accessible for a longer time.

## Acceptance criteria

- [ ] favorits are stored in cloudinary

## Tasks

- [ ] branch
- [ ] safe pictures by Dall E via url to cloudinary
- [ ] add them to a new mongoDB in order to keep them accessible for future features
