### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by t0bbl** [t0bbl/capstone-project#29]
## Value proposition

As a User
I want to have a direct link to my favorites, a back button and a link to home
in order to access the page easier and faster

## Description

![Screenshot 2023-05-19 at 11 03 30](https://github.com/t0bbl/capstone-project/assets/117731660/e5c6232a-b496-4eff-9cc1-e6b69f8bf7bd)

## Acceptance criteria

- [ ] the footer is shown on all pages 
- [ ] the links take the user to the corresponding page

## Tasks

- [ ] branch
- [ ] design footer
- [ ] establish links
- [ ] implement footer on all pages

**Comment by marte1337** [comment]
LGTM!
