### ISSUE TITLE
Refactor and link to Preview Page from Favorites and AlltimeFavorites

### ISSUE THREAD

**Issue by t0bbl** [t0bbl/capstone-project#33]
## Value proposition

As a User
I want to see the Preview Page when i click on one of my or one of the AlltimeFavorites
in order to safe or order the design.

## Description

[image of wireframe]

## Acceptance criteria

- [ ] when you click on an alltime Favorite you get taken to the details page
- [ ] when you click on one of your Favorites you get taken to the details page

## Tasks

- [ ] wrap the Favorites in Links to their respective details page
- [ ] refactor the code to make it better readable
- [ ] fix a small design flaw in the loading page
- [ ] order the alltime Favorites after number of favorites
