### ISSUE TITLE
Favorite Designs

### ISSUE THREAD

**Issue by t0bbl** [t0bbl/capstone-project#6]
## Value proposition

As a user
I want to see random designs
in order to fav them

## Description

![Screenshot 2023-04-26 at 16 32 25](https://user-images.githubusercontent.com/117731660/234609127-c89f9a39-2b46-46fb-adab-f1817adf5b03.png)

## Acceptance criteria

- [ ] i get random pictures shown
- [ ] the pictures are favorites of me or someone else
- [ ] i can fav and unfav on the page

## Tasks

- [ ] Branch
- [ ] create a page for random images
- [ ] create a system for loading the next pictures while scrolling

**Comment by NikRoe** [comment]
Hi Robin,

I would strongly suggest splitting this user story into several smaller ones.

I propose having a user story for:
- Favourites
- Rating System
- Random Images shown

Also, there are no other people in your app yet, so in your Value Proposition it would make more sense to have something like this (example for Favourites):
As a user
I want to mark designs as favourite
in order to have a collection of my liked designs.

If, for instance, you choose to go with the favourites next, you should include wireframes displaying how a design marked as a favourite looks vs. a design that has not been marked as favourite

**Comment by t0bbl** [comment]
thanks, iam going to rework this frame into smaller ones, just like you said.

**Comment by KivancUlucan** [comment]
LGTM!
