### ISSUE TITLE
Rating Page

### ISSUE THREAD

**Issue by t0bbl** [t0bbl/capstone-project#9]
## Value proposition

As a user
I want to see random designs
in order to rate and fav them

## Description

![Screenshot 2023-04-26 at 10 56 19](https://user-images.githubusercontent.com/117731660/234607146-9367d477-05c4-4b0f-bfaf-c1c0cee4b959.png)

## Acceptance criteria

- [ ] i get 3 random pictures shown
- [ ] the page loads the next 3 when i scroll down

## Tasks

- [ ] Branch
- [ ] create a page for random images
- [ ] create a system for loading the next pictures while scrolling

**Comment by ketnek** [comment]
Servus,

looks good to me. The only thing I saw. There is a favorite button. Is that a placeholder or does it works? If not I would recommend to remove it.
